
#ifndef DRCR_H
#define DRCR_H

typedef uint32_t RESOURCE_ID;
typedef union DRC_TYPE RESOURCE_TYPE;
typedef MEMORY_HANDLE RESOURCE_BITMAP_HANDLE;
typedef MEMORY_HANDLE RESOURCE_JSON_HANDLE;

#endif /* DRCR_H */

