#!/bin/bash
make -f Makefile.sdl RESOURCE=FILE FMT_JSON=TRUE BUILD=RELEASE pkg_sdl && \
make -f Makefile.sdl DEPTH=VGA RESOURCE=FILE FMT_JSON=TRUE BUILD=RELEASE pkg_sdl && \
make -f Makefile.palm BUILD=RELEASE DEPTH=MONO pkg_palm
#make RESOURCE=FILE FMT_JSON=TRUE BUILD=RELEASE pkg_xlib && \
#make RESOURCE=FILE FMT_ASN=TRUE BUILD=RELEASE ARCFMT=ZIP pkg_dos && \
#make RESOURCE=FILE FMT_JSON=TRUE BUILD=RELEASE ARCFMT=ZIP pkg_win32 && \
#make RESOURCE=FILE FMT_ASN=TRUE BUILD=RELEASE ARCFMT=ZIP pkg_win16

