#!/bin/bash
make BUILD=RELEASE pkg_palm && \
make RESOURCE=FILE FMT_JSON=TRUE BUILD=RELEASE pkg_sdl && \
make RESOURCE=FILE FMT_JSON=TRUE BUILD=RELEASE pkg_xlib && \
make RESOURCE=FILE FMT_ASN=TRUE BUILD=RELEASE ARCFMT=ZIP pkg_dos && \
make RESOURCE=FILE FMT_JSON=TRUE BUILD=RELEASE ARCFMT=ZIP pkg_win32 && \
make RESOURCE=FILE FMT_ASN=TRUE BUILD=RELEASE ARCFMT=ZIP pkg_win16

