
#ifndef DOSI_H
#define DOSI_H

#define INPUT_KEY_A 97
#define INPUT_KEY_B 98
#define INPUT_KEY_C 99
#define INPUT_KEY_D 100
#define INPUT_KEY_E 101
#define INPUT_KEY_F 102
#define INPUT_KEY_G 103
#define INPUT_KEY_H 104
#define INPUT_KEY_I 105
#define INPUT_KEY_J 106
#define INPUT_KEY_K 107
#define INPUT_KEY_L 108
#define INPUT_KEY_M 109
#define INPUT_KEY_N 110
#define INPUT_KEY_O 111
#define INPUT_KEY_P 112
#define INPUT_KEY_Q 113
#define INPUT_KEY_R 114
#define INPUT_KEY_S 115
#define INPUT_KEY_T 116
#define INPUT_KEY_U 117
#define INPUT_KEY_V 118
#define INPUT_KEY_W 119
#define INPUT_KEY_X 120
#define INPUT_KEY_Y 121
#define INPUT_KEY_Z 122

#define INPUT_KEY_LEFT INPUT_KEY_A
#define INPUT_KEY_RIGHT INPUT_KEY_D
#define INPUT_KEY_UP INPUT_KEY_W
#define INPUT_KEY_DOWN INPUT_KEY_S
#define INPUT_KEY_QUIT INPUT_KEY_Q
#define INPUT_KEY_OK INPUT_KEY_Z

#endif /* DOSI_H */

